// <auto-generated />
using LocalLookUp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LocalLookUp.Migrations
{
    [DbContext(typeof(LocalLookUpContext))]
    [Migration("20220123171414_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("LocalLookUp.Models.Town", b =>
                {
                    b.Property<int>("TownId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Restaurant")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Shop")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("TownId");

                    b.ToTable("Towns");

                    b.HasData(
                        new
                        {
                            TownId = 1,
                            Name = "Bakersfield",
                            Restaurant = "BakersFelid Pub",
                            Shop = "Karens Curiosities"
                        },
                        new
                        {
                            TownId = 2,
                            Name = "Andalusia",
                            Restaurant = "Dessert Pizza",
                            Shop = "Aquari"
                        },
                        new
                        {
                            TownId = 3,
                            Name = "Matilda",
                            Restaurant = "Jeff's Joe Hut",
                            Shop = "Antique 4 You"
                        },
                        new
                        {
                            TownId = 4,
                            Name = "Chickasaw",
                            Restaurant = "Smoked Everything",
                            Shop = "SmokeShop"
                        },
                        new
                        {
                            TownId = 5,
                            Name = "Bartholomew",
                            Restaurant = "Bistro",
                            Shop = "Avantgarde"
                        },
                        new
                        {
                            TownId = 6,
                            Name = "Florence",
                            Restaurant = "Miltons Wing Stop",
                            Shop = "Capella's Cloths Bin"
                        },
                        new
                        {
                            TownId = 7,
                            Name = "Guntersville",
                            Restaurant = "Woolly Mammoth Burgers",
                            Shop = "All You Need Pet Emporium"
                        },
                        new
                        {
                            TownId = 8,
                            Name = "Ozark",
                            Restaurant = "Route 64 Diner",
                            Shop = "711"
                        },
                        new
                        {
                            TownId = 9,
                            Name = "Spokane",
                            Restaurant = "Grease Palace",
                            Shop = "Guns Guns and more Guns"
                        },
                        new
                        {
                            TownId = 10,
                            Name = "Selma",
                            Restaurant = "Selma Sandwhich Stop",
                            Shop = "Selma Crystals"
                        },
                        new
                        {
                            TownId = 11,
                            Name = "Walpi",
                            Restaurant = "Teryaki Walipi",
                            Shop = "Surfs Up"
                        },
                        new
                        {
                            TownId = 12,
                            Name = "Yuma",
                            Restaurant = "Bob's Breakfast",
                            Shop = "Put Put golf Spot"
                        },
                        new
                        {
                            TownId = 13,
                            Name = "Calexio",
                            Restaurant = "Gastues",
                            Shop = "Kyras Textiles"
                        },
                        new
                        {
                            TownId = 14,
                            Name = "Barstow",
                            Restaurant = "Barstow College Pub",
                            Shop = "Oran Organic"
                        },
                        new
                        {
                            TownId = 15,
                            Name = "Puslbo",
                            Restaurant = "Grill King",
                            Shop = "Orca Sounds Trinkets"
                        },
                        new
                        {
                            TownId = 16,
                            Name = "Scottsdale",
                            Restaurant = "Ricky's",
                            Shop = "Duck Hunting supply"
                        },
                        new
                        {
                            TownId = 17,
                            Name = "Marysville",
                            Restaurant = "Mama Roo's",
                            Shop = "Hillbit Nursery"
                        },
                        new
                        {
                            TownId = 18,
                            Name = "San Mateo",
                            Restaurant = "Gastues",
                            Shop = "Kyras Textiles"
                        },
                        new
                        {
                            TownId = 19,
                            Name = "Fall River",
                            Restaurant = "Orion",
                            Shop = "Beatrice Bagel"
                        },
                        new
                        {
                            TownId = 20,
                            Name = "Groton",
                            Restaurant = "Goreton River Grill",
                            Shop = "Bait and Fish"
                        },
                        new
                        {
                            TownId = 21,
                            Name = "Willmar",
                            Restaurant = "Rebel Rouseres",
                            Shop = "Spaghetti Factory"
                        },
                        new
                        {
                            TownId = 22,
                            Name = "Missoula",
                            Restaurant = "Corenell's Chicken",
                            Shop = "Om Bap"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
